### ISSUE TITLE
Config-example.toml

### ISSUE THREAD

**Issue by eyal1izhaki** [diericx/iceetime#43]
https://github.com/diericx/iceetime/blob/631c02db826d64ae1edfccc332faf233d77561d8/config-example.toml#L25
https://github.com/diericx/iceetime/blob/631c02db826d64ae1edfccc332faf233d77561d8/config-example.toml#L28
Should be [transcoder.video] and [transcoder.audio], am i right?
I didn't know why im keep getting this **Transcoder is invalid: Video format cannot be empty string** error when using the config-example file.. toml format i pretty new to me :)

**Comment by diericx** [comment]
Shoot yes! I'm always forgetting to update the config-example file. Is it working for you now?

**Comment by eyal1izhaki** [comment]
Yes but i'm struggling with some another problems...

**Comment by diericx** [comment]
Ok, let me know if you want any help troubleshooting. You are one of the first people to try getting this running so I'll follow closely behind and add any hurdles you run into to the documentation (even if it isn't specific to Iceetime).

**Comment by eyal1izhaki** [comment]
Thanks a lot! As you see im still learning to use github so i'll try not to do weird things like closing and opening issues multiple times..😂

**Comment by diericx** [comment]
hahaha that's ok
