### ISSUE TITLE
Add TMDB bindings in go

### ISSUE THREAD

**Issue by diericx** [diericx/iceetime#5]
Before we can add any search functionality we need to incorporate TMDB bindings to get search results and metadata for movies.

- Add TMDB API key (`tmdb_api_key` in toml, `TMDBAPIKey` in Go) to [TOML config](https://github.com/diericx/iceetime/blob/1a7790e6f378c79b5ef22702bf2c6d32b4f70786/cmd/main.go#L18)
- Add a new `repo` in `internal/app/repos/tmdb` which takes in the `TMDBAPIKey` string and implements these functions
  - PopularMovies() []Movie
[API Call](https://github.com/diericx/iceetime/blob/1a7790e6f378c79b5ef22702bf2c6d32b4f70786/frontend/src/pages/movies.js#L51)
  - GetMovie(tmdbID string) Movie
[API Call](https://github.com/diericx/iceetime/blob/1a7790e6f378c79b5ef22702bf2c6d32b4f70786/frontend/src/pages/movie.js#L29) 
  - SearchMovie(query string) []Movie
[API Call](https://github.com/diericx/iceetime/blob/1a7790e6f378c79b5ef22702bf2c6d32b4f70786/frontend/src/pages/search.js#L29)

**Comment by diericx** [comment]
Hey @ravindrabhargava ! We don't have a bot watching this stuff. Are you interested in working on this issue?

**Comment by ravindrabhargava** [comment]
Hi,
Yes I would like to understand better and work on it. Thanks

**Comment by diericx** [comment]
Great! I updated the description to have more info and I will be working on this project all day tomorrow and some over this weekend if you have any questions :)
