### ISSUE TITLE
Update config-example.toml

### ISSUE THREAD

**Issue by filipef101** [diericx/iceetime#53]
I get this a bunch of times then exists: 

`ERROR: Invalid config
bevy       | Release Service is invalid: Quality 0 is invalid:
bevy       | {Name:720p Regex:720 MinSize:5e+08 MaxSize:1e+10 MinSeeders:2 Resolution:1280x720 SeederScoreExpr: SizeScoreExpr:}
bevy       |  Seeder score function cannot be emptyERROR: Invalid config
`

**Comment by filipef101** [comment]
Seems, not I tried to make it work with changes based on the PR that broke it https://github.com/diericx/bevy/pull/52  but kind of gave up for now

**Comment by filipef101** [comment]
While at it, I think the jackett endpoint should change to  `api/v2.0/indexers/all/results`

**Comment by diericx** [comment]
Hey, really sorry about this! I helped someone else fix this but totally forgot to update the example config. I'll update it after I get some coffee :)

**Comment by diericx** [comment]
Might make sense to just generate the config file with some defaults if it doesn't exist
